# GolangCI configuration for kubectl-kaito plugin
---
version: "2"

run:
  timeout: 10m
  tests: true

linters:
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - gocognit
  disable:
    - errcheck

linters-settings:
  govet:
    check-shadowing: true

  misspell:
    locale: US
  gocognit:
    min-complexity: 15

  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - gocognit
        - errcheck
        - gosec
    - path: main\.go
      linters:
        - gosec
