apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kaito
spec:
  version: v0.1.0
  homepage: https://github.com/kaito-project/kaito-kubectl-plugin
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/kaito-project/kaito-kubectl-plugin/releases/download/v0.1.0/kubectl-kaito-0.1.0-linux-amd64.tar.gz
    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    files:
    - from: "./kubectl-kaito"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "kubectl-kaito"
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/kaito-project/kaito-kubectl-plugin/releases/download/v0.1.0/kubectl-kaito-0.1.0-linux-arm64.tar.gz
    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    files:
    - from: "./kubectl-kaito"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "kubectl-kaito"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/kaito-project/kaito-kubectl-plugin/releases/download/v0.1.0/kubectl-kaito-0.1.0-darwin-amd64.tar.gz
    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    files:
    - from: "./kubectl-kaito"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "kubectl-kaito"
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/kaito-project/kaito-kubectl-plugin/releases/download/v0.1.0/kubectl-kaito-0.1.0-darwin-arm64.tar.gz
    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    files:
    - from: "./kubectl-kaito"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "kubectl-kaito"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/kaito-project/kaito-kubectl-plugin/releases/download/v0.1.0/kubectl-kaito-0.1.0-windows-amd64.tar.gz
    sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5
    files:
    - from: "./kubectl-kaito.exe"
      to: "."
    - from: "./LICENSE"
      to: "."
    bin: "kubectl-kaito.exe"
  shortDescription: Manage AI/ML model inference and fine-tuning with Kaito
  description: |
    kubectl-kaito is a command-line tool for managing AI/ML model inference 
    and RAG (Retrieval-Augmented Generation) workloads using the Kubernetes 
    AI Toolchain Operator (Kaito).

    This plugin simplifies the deployment, management, and monitoring of AI models
    in Kubernetes clusters through Kaito workspaces and RAG engines.

    Features:
    - Deploy AI models for inference with automatic GPU provisioning
    - Manage workspace lifecycle and monitor status with real-time updates
    - Interactive chat with deployed models using OpenAI-compatible API
    - Deploy and query RAG engines for document-based question answering
    - Discover and validate available model presets from Kaito repository
    - Get inference endpoints for programmatic access to deployed models

