apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kaito
spec:
  version: v0.1.0
  homepage: https://github.com/kaito-project/kubectl-kaito
  shortDescription: Manage AI/ML model inference and fine-tuning with Kaito
  description: |
    kubectl-kaito is a command-line tool for managing AI/ML model inference 
    and fine-tuning workloads using the Kubernetes AI Toolchain Operator (Kaito).

    This plugin simplifies the deployment, management, and monitoring of AI models
    in Kubernetes clusters through Kaito workspaces.

    Features:
    - Deploy AI models for inference with automatic GPU provisioning
    - Fine-tune models with custom datasets using QLora and LoRA techniques  
    - Monitor workspace status with real-time updates
    - View logs from inference and training workloads
    - Discover available model presets for various AI model families
    - Delete workspaces with proper cleanup of GPU resources

  caveats: |
    This plugin requires:
    - Kubernetes cluster with Kaito operator installed
    - kubectl configured to access your cluster
    - Sufficient Azure VM quota for GPU instances (when using Azure)

  platforms:
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-linux-amd64.tar.gz
      sha256: "TBD"
      bin: kubectl-kaito
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-linux-arm64.tar.gz
      sha256: "TBD"
      bin: kubectl-kaito
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-darwin-amd64.tar.gz
      sha256: "TBD"
      bin: kubectl-kaito
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-darwin-arm64.tar.gz
      sha256: "TBD"
      bin: kubectl-kaito
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-windows-amd64.zip
      sha256: "TBD"
      bin: kubectl-kaito.exe
