apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kaito
spec:
  version: v0.1.0
  homepage: https://github.com/kaito-project/kubectl-kaito
  shortDescription: Manage AI/ML model inference and fine-tuning with Kaito
  description: |
    kubectl-kaito is a command-line tool for managing AI/ML model inference 
    and RAG (Retrieval-Augmented Generation) workloads using the Kubernetes 
    AI Toolchain Operator (Kaito).

    This plugin simplifies the deployment, management, and monitoring of AI models
    in Kubernetes clusters through Kaito workspaces and RAG engines.

    Features:
    - Deploy AI models for inference with automatic GPU provisioning
    - Manage workspace lifecycle and monitor status with real-time updates
    - Interactive chat with deployed models using OpenAI-compatible API
    - Deploy and query RAG engines for document-based question answering
    - Discover and validate available model presets from Kaito repository
    - Get inference endpoints for programmatic access to deployed models

  caveats: |
    This plugin requires:
    - Kubernetes cluster with Kaito operator installed
    - kubectl configured to access your cluster
    - Sufficient Azure VM quota for GPU instances (when using Azure)

  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-linux-amd64.tar.gz
    sha256: "00f073dad85d29de4ca74402a9b587d083f53b3f55eef77494b3f188ad897b6a"
    bin: kubectl-kaito
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-linux-arm64.tar.gz
    sha256: "592bf17cfae945905a509a955883c2a99cace1c1a942ee1701eb6fbd801a90b9"
    bin: kubectl-kaito
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-darwin-amd64.tar.gz
    sha256: "4fb70104f922046c9c815750c13d4ba6cfab37539aadd8beb3d5a257c5d76978"
    bin: kubectl-kaito
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-darwin-arm64.tar.gz
    sha256: "8a6f5e3e8d01cfa1376544a2878781a746bf97aae97da192099b5afa3c5f328d"
    bin: kubectl-kaito
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/kaito-project/kubectl-kaito/releases/download/v0.1.0/kubectl-kaito-v0.1.0-windows-amd64.zip
    sha256: "3609d8ffdfaadafb48e7d3d4c06ee6b4507cc24a54e6f2bb12e97ef47b421839"
    bin: kubectl-kaito.exe
